import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Button, ErrorText, Field } from '../components/ui';
import { api } from '../services/api';
import { colors } from '../theme';
import { AnswerStyle, RootStackParamList } from '../types';
import { useAuth } from '../context/AuthContext';

export function WelcomeScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'Welcome'>) { return <View style={s.welcome}><View style={s.logo}><Text style={{ fontSize: 32, fontWeight: '800', color: 'white' }}>M</Text></View><Text style={s.hero}>Everyday help,{`\n`}made simple.</Text><Text style={s.sub}>A friendly assistant for writing, planning, shopping, work, and all the little things.</Text><View style={{ width: '100%', gap: 12 }}><Button title="Create Account" onPress={() => navigation.navigate('Register')} /><Button title="Sign In" secondary onPress={() => navigation.navigate('Login')} /><Pressable onPress={() => navigation.navigate('FirstSetup', { guest: true })}><Text style={s.guest}>Continue as Guest</Text></Pressable></View></View>; }

function AuthForm({ mode, navigation }: { mode: 'login' | 'register'; navigation: any }) { const { saveSession } = useAuth(); const [firstName, setFirstName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit() { if (!email.trim() || !password) return setError('Please complete all required fields.'); if (mode === 'register' && password !== confirm) return setError('Passwords do not match.'); setLoading(true); setError(''); try { const result = mode === 'login' ? await api.login({ email, password }) : await api.register({ firstName, email, password }); await saveSession(result.token); navigation.replace(mode === 'register' ? 'FirstSetup' : 'Main', mode === 'register' ? { firstName } : undefined); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to continue.'); } finally { setLoading(false); } } return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView contentContainerStyle={s.form} keyboardShouldPersistTaps="handled"><Text style={s.title}>{mode === 'login' ? 'Good to see you' : 'Let’s get started'}</Text><Text style={s.sub}>{mode === 'login' ? 'Sign in to pick up where you left off.' : 'Just the basics — you can add more later.'}</Text>{mode === 'register' && <Field label="First name" value={firstName} onChangeText={setFirstName} autoCapitalize="words" />}<Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry />{mode === 'register' && <Field label="Confirm password" value={confirm} onChangeText={setConfirm} secureTextEntry />}<ErrorText message={error} />{mode === 'login' && <Pressable><Text style={{ color: colors.green, fontWeight: '600' }}>Forgot password?</Text></Pressable>}<Button title={loading ? 'Please wait…' : mode === 'login' ? 'Sign In' : 'Create Account'} disabled={loading} onPress={submit} /></ScrollView></KeyboardAvoidingView>; }
export const LoginScreen = ({ navigation }: any) => <AuthForm mode="login" navigation={navigation} />;
export const RegisterScreen = ({ navigation }: any) => <AuthForm mode="register" navigation={navigation} />;

const styles: AnswerStyle[] = ['Short and simple', 'Normal', 'Detailed']; const categories = ['Daily life', 'Writing', 'Planning', 'Shopping', 'Work', 'Money'];
export function FirstSetupScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'FirstSetup'>) { const { setProfile, saveSession } = useAuth(); const [name, setName] = useState(route.params?.firstName || ''); const [country, setCountry] = useState(''); const [answerStyle, setAnswerStyle] = useState<AnswerStyle>('Normal'); const [category, setCategory] = useState('Daily life'); const [saving, setSaving] = useState(false); async function finish() { if (!name.trim() || !country.trim()) return; setSaving(true); const profile = { firstName: name.trim(), country: country.trim(), preferredResponseStyle: answerStyle, primaryHelpCategory: category }; try { if (route.params?.guest) { await AsyncStorage.setItem('guestProfile', JSON.stringify(profile)); await saveSession('guest'); } else await api.updateProfile(profile); setProfile(profile); navigation.replace('Main'); } finally { setSaving(false); } } return <ScrollView contentContainerStyle={s.form}><Text style={s.title}>Let’s teach your assistant a little about you.</Text><Text style={s.sub}>Only a few helpful details. Nothing intrusive.</Text><Field label="What should I call you?" value={name} onChangeText={setName} /><Field label="Country" value={country} onChangeText={setCountry} /><Choice title="Preferred answer style" values={styles} selected={answerStyle} onSelect={v => setAnswerStyle(v as AnswerStyle)} /><Choice title="What would you most like help with?" values={categories} selected={category} onSelect={setCategory} /><Button title={saving ? 'Saving…' : 'Finish setup'} disabled={!name.trim() || !country.trim() || saving} onPress={finish} /></ScrollView>; }
function Choice({ title, values, selected, onSelect }: { title: string; values: string[]; selected: string; onSelect: (v: string) => void }) { return <View style={{ gap: 9 }}><Text style={{ fontWeight: '700', color: colors.ink, fontSize: 16 }}>{title}</Text><View style={s.chips}>{values.map(v => <Pressable key={v} onPress={() => onSelect(v)} style={[s.chip, selected === v && s.chipSelected]}><Text style={{ color: selected === v ? 'white' : colors.ink, fontWeight: '600' }}>{v}</Text></Pressable>)}</View></View>; }
const s = StyleSheet.create({ welcome: { flex: 1, padding: 28, paddingTop: 110, backgroundColor: colors.cream, alignItems: 'center', gap: 24 }, logo: { width: 70, height: 70, borderRadius: 22, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, hero: { fontSize: 36, lineHeight: 43, textAlign: 'center', color: colors.ink, fontWeight: '800' }, title: { fontSize: 28, lineHeight: 35, color: colors.ink, fontWeight: '800' }, sub: { color: colors.muted, fontSize: 17, lineHeight: 25, textAlign: 'center' }, guest: { color: colors.green, textAlign: 'center', padding: 10, fontSize: 16, fontWeight: '600' }, form: { flexGrow: 1, padding: 24, gap: 20, backgroundColor: colors.cream }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, chip: { paddingHorizontal: 15, paddingVertical: 11, borderRadius: 22, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border }, chipSelected: { backgroundColor: colors.green, borderColor: colors.green } });
