import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, ErrorText, Field } from '../components/ui';
import { api } from '../services/api';
import { card, colors } from '../theme';
import { PayFrequency } from '../types';

const pays:{label:string;value:PayFrequency}[]=[{label:'Weekly',value:'weekly'},{label:'Every 2 weeks',value:'every_2_weeks'},{label:'Twice a month',value:'twice_monthly'},{label:'Monthly',value:'monthly'},{label:'Other',value:'other'}];
const billCategories=['Housing','Utilities','Phone','Internet','Transportation','Insurance','Debt','Subscriptions','Childcare','Other'];
const today=new Date().toISOString().slice(0,10);
export function BudgetSetupScreen({navigation}:any){
 const [step,setStep]=useState(1),[payFrequency,setPayFrequency]=useState<PayFrequency>('every_2_weeks'),[pay,setPay]=useState(''),[payDate,setPayDate]=useState(today),[savings,setSavings]=useState('0'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [bill,setBill]=useState({name:'',amount:'',nextDueDate:today,frequency:'monthly' as const,category:'Housing'}); const [targets,setTargets]=useState<Record<string,string>>({Food:'',Gas:'',Shopping:'',Entertainment:'',Other:''});
 const next=()=>{if(step===2&&(!Number(pay)||!payDate)){setError('Enter your usual take-home pay and next payday.');return;}setError('');setStep(x=>x+1)};
 const finish=async()=>{setSaving(true);setError('');try{await api.saveBudget({payFrequency,typicalTakeHome:Number(pay),nextPayDate:payDate,monthlySavingsTarget:Number(savings)||0,categories:Object.entries(targets).filter(([,v])=>Number(v)>0).map(([name,v])=>({name,monthlyTarget:Number(v)}))});if(bill.name&&Number(bill.amount)>0)await api.addBill({...bill,amount:Number(bill.amount),active:true});navigation.replace('Money');}catch(e:any){setError(e.message);}finally{setSaving(false)}};
 return <ScrollView style={s.screen} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.progress}>Step {step} of 5</Text>
 {step===1&&<Panel title="How often are you paid?">{pays.map(p=><Choice key={p.value} label={p.label} selected={payFrequency===p.value} onPress={()=>setPayFrequency(p.value)}/>)}</Panel>}
 {step===2&&<Panel title="What is your typical take-home pay?"><Field label="Take-home pay" value={pay} onChangeText={setPay} keyboardType="decimal-pad" placeholder="$1,800"/><Field label="Next payday (YYYY-MM-DD)" value={payDate} onChangeText={setPayDate}/><Text style={s.help}>Use the amount that reaches you after taxes and deductions.</Text></Panel>}
 {step===3&&<Panel title="Add a recurring bill"><Text style={s.help}>You can add more bills from the Money screen later, or leave this blank for now.</Text><Field label="Name" value={bill.name} onChangeText={v=>setBill({...bill,name:v})} placeholder="Electric"/><Field label="Amount" value={bill.amount} onChangeText={v=>setBill({...bill,amount:v})} keyboardType="decimal-pad" placeholder="$86"/><Field label="Next due date (YYYY-MM-DD)" value={bill.nextDueDate} onChangeText={v=>setBill({...bill,nextDueDate:v})}/><Text style={s.label}>Category</Text><View style={s.wrap}>{billCategories.map(c=><Choice compact key={c} label={c} selected={bill.category===c} onPress={()=>setBill({...bill,category:c})}/>)}</View></Panel>}
 {step===4&&<Panel title="Do you want to set money aside regularly?"><Field label="Fixed monthly savings (enter 0 for no target)" value={savings} onChangeText={setSavings} keyboardType="decimal-pad" placeholder="$200"/><Text style={s.help}>This is a planning target, not money moved from your bank.</Text></Panel>}
 {step===5&&<Panel title="Plan flexible spending"><Text style={s.help}>Optional fixed dollar targets. No percentages required.</Text>{Object.keys(targets).map(name=><Field key={name} label={`${name} monthly target`} value={targets[name]} onChangeText={v=>setTargets({...targets,[name]:v})} keyboardType="decimal-pad" placeholder="$0"/>)}</Panel>}
 <ErrorText message={error}/><View style={s.buttons}>{step>1&&<Button title="Back" secondary onPress={()=>setStep(x=>x-1)}/>}<Button title={step===5?(saving?'Saving…':'Finish setup'):'Continue'} disabled={saving} onPress={step===5?finish:next}/></View></ScrollView>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <View style={s.panel}><Text style={s.title}>{title}</Text>{children}</View>};
function Choice({label,selected,onPress,compact=false}:{label:string;selected:boolean;onPress:()=>void;compact?:boolean}){return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={onPress} style={[s.choice,compact&&s.compact,selected&&s.selected]}><Text style={[s.choiceText,selected&&s.selectedText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({screen:{backgroundColor:colors.cream},page:{padding:20,gap:14,paddingBottom:40},progress:{color:colors.green,fontWeight:'700'},panel:{...card,gap:13},title:{fontSize:22,fontWeight:'800',color:colors.ink},help:{color:colors.muted,lineHeight:20},label:{color:colors.ink,fontWeight:'600'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{borderWidth:1,borderColor:colors.border,borderRadius:13,padding:14,backgroundColor:colors.white},compact:{paddingVertical:9,paddingHorizontal:11},selected:{backgroundColor:colors.paleGreen,borderColor:colors.green},choiceText:{color:colors.ink},selectedText:{color:colors.green,fontWeight:'700'},buttons:{gap:10}});
