import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, ErrorText, Field } from '../components/ui';
import { api } from '../services/api';
import { card, colors } from '../theme';
import { Budget, MoneySummary, MoneyTransaction, RecurringBill, SavingsGoal } from '../types';

const today=()=>new Date().toISOString().slice(0,10); const dollars=(n:number)=>`$${n.toLocaleString(undefined,{maximumFractionDigits:2})}`;
const friendlyDate=(date:string)=>{const d=new Date(`${date}T12:00:00`),now=new Date();const days=Math.round((+d-new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime())/86400000);if(days===0)return'Today';if(days===1)return'Tomorrow';if(days<7&&days>0)return d.toLocaleDateString([],{weekday:'long'});return d.toLocaleDateString([],{month:'short',day:'numeric'});};
export function MoneyScreen({navigation}:any){
 const [summary,setSummary]=useState<MoneySummary>(),[budget,setBudget]=useState<Budget|null>(),[bills,setBills]=useState<RecurringBill[]>([]),[transactions,setTransactions]=useState<MoneyTransaction[]>([]),[goals,setGoals]=useState<SavingsGoal[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const [showTransaction,setShowTransaction]=useState(false),[showBill,setShowBill]=useState(false),[editingBill,setEditingBill]=useState<string|null>(null),[afford,setAfford]=useState(''),[affordAnswer,setAffordAnswer]=useState('');
 const [tx,setTx]=useState({description:'',amount:'',category:'Food',type:'expense' as 'expense'|'income',transactionDate:today()}); const [bill,setBill]=useState({name:'',amount:'',category:'Housing',frequency:'monthly' as const,nextDueDate:today()});
 const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError('');try{const [s,b,bs,ts,gs]=await Promise.all([api.moneySummary(),api.getBudget(),api.getBills(),api.getTransactions(),api.getGoals()]);setSummary(s);setBudget(b);setBills(bs);setTransactions(ts);setGoals(gs);}catch(e:any){setError(e.message);}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{load()},[load]);
 const addTx=async()=>{if(!tx.description||!Number(tx.amount)){setError('Enter a description and amount.');return;}try{await api.addTransaction({...tx,amount:Number(tx.amount),source:'manual'});setShowTransaction(false);setTx({...tx,description:'',amount:''});await load();}catch(e:any){setError(e.message)}};
 const addBill=async()=>{if(!bill.name||!Number(bill.amount)){setError('Enter a bill name and amount.');return;}try{const payload={...bill,amount:Number(bill.amount),active:true};if(editingBill)await api.updateBill(editingBill,payload);else await api.addBill(payload);setShowBill(false);setEditingBill(null);setBill({...bill,name:'',amount:''});await load();}catch(e:any){setError(e.message)}};
 const paid=async(b:RecurringBill)=>{const next=new Date(`${b.nextDueDate}T12:00:00`);next.setMonth(next.getMonth()+1);await api.updateBill(b.id,{nextDueDate:next.toISOString().slice(0,10)});load();};
 const remove=(b:RecurringBill)=>Alert.alert('Delete this bill?',`${b.name} will no longer appear in your plan.`,[{text:'Keep it',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await api.deleteBill(b.id);load()}}]);
 const checkAfford=async()=>{if(!Number(afford))return;try{const r=await api.canIAfford(Number(afford));setAffordAnswer(r.message)}catch(e:any){setError(e.message)}};
 if(loading)return <View style={s.center}><ActivityIndicator color={colors.green}/><Text style={s.muted}>Working out your estimate…</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)}/>} keyboardShouldPersistTaps="handled"><ErrorText message={error}/>
 <View style={s.hero}><Text style={s.eyebrow}>AVAILABLE TODAY</Text>{summary?.availableToday==null?<><Text style={s.heroText}>Let’s set up your budget.</Text><Text style={s.muted}>I need a little more budget information before I can estimate this.</Text><Button title="Set Up Budget" onPress={()=>navigation.navigate('BudgetSetup')}/></>:<><Text style={s.amount}>{dollars(summary.availableToday)}</Text><Text style={s.heroText}>{summary.plainEnglishSummary}</Text><Text style={s.disclaimer}>Planning estimate — not a confirmed bank balance. Based only on what you entered.</Text></>}</View>
 <Section title="Upcoming bills" action="Add bill" onAction={()=>setShowBill(!showBill)}>{showBill&&<View style={s.form}><Field label="Bill name" value={bill.name} onChangeText={v=>setBill({...bill,name:v})}/><Field label="Amount" value={bill.amount} onChangeText={v=>setBill({...bill,amount:v})} keyboardType="decimal-pad"/><Field label="Next due date (YYYY-MM-DD)" value={bill.nextDueDate} onChangeText={v=>setBill({...bill,nextDueDate:v})}/><Button title={editingBill?"Update bill":"Save bill"} onPress={addBill}/></View>}{bills.length?bills.map(b=><View style={s.item} key={b.id}><View style={s.grow}><Text style={s.date}>{friendlyDate(b.nextDueDate)}</Text><Text style={s.itemTitle}>{b.name} — {dollars(b.amount)}</Text><Text style={s.muted}>{b.category}</Text></View><View><Mini label="Mark paid" onPress={()=>paid(b)}/><Mini label="Edit" onPress={()=>{setBill({name:b.name,amount:String(b.amount),category:b.category,frequency:b.frequency as any,nextDueDate:b.nextDueDate});setEditingBill(b.id);setShowBill(true)}}/><Mini label="Skip once" onPress={()=>paid(b)}/><Mini label="Delete" onPress={()=>remove(b)}/></View></View>):<Text style={s.muted}>No bills added yet.</Text>}</Section>
 <Section title="Income"><Text style={s.itemTitle}>{budget?`${dollars(budget.typicalTakeHome)} each pay period`:'Add your usual pay during budget setup.'}</Text>{budget&&<Text style={s.muted}>Next pay: {friendlyDate(budget.nextPayDate)}</Text>}</Section>
 <Section title="Spending" action="Add transaction" onAction={()=>setShowTransaction(!showTransaction)}>{showTransaction&&<View style={s.form}><Field label="Description" value={tx.description} onChangeText={v=>setTx({...tx,description:v})} placeholder="Lunch"/><Field label="Amount" value={tx.amount} onChangeText={v=>setTx({...tx,amount:v})} keyboardType="decimal-pad"/><Field label="Category" value={tx.category} onChangeText={v=>setTx({...tx,category:v})}/><View style={s.row}><Mini label="Expense" active={tx.type==='expense'} onPress={()=>setTx({...tx,type:'expense'})}/><Mini label="Income" active={tx.type==='income'} onPress={()=>setTx({...tx,type:'income'})}/></View><Field label="Date (YYYY-MM-DD)" value={tx.transactionDate} onChangeText={v=>setTx({...tx,transactionDate:v})}/><Button title="Add transaction" onPress={addTx}/></View>}{transactions.slice(0,5).map(t=><View key={t.id} style={s.line}><Text style={s.grow}>{t.description}<Text style={s.muted}>  {t.category}</Text></Text><Text style={[s.itemTitle,t.type==='income'&&{color:colors.green}]}>{t.type==='income'?'+':'−'}{dollars(t.amount)}</Text></View>)}{!transactions.length&&<Text style={s.muted}>Add spending as it happens. Your daily estimate will update.</Text>}</Section>
 <Section title="Savings goals"><Text style={s.itemTitle}>{budget?.monthlySavingsTarget?`${dollars(budget.monthlySavingsTarget)} set aside each month`:'No regular savings target yet.'}</Text>{goals.map(g=><Text key={g.id} style={s.muted}>{g.name}: {dollars(g.currentAmount)} of {dollars(g.targetAmount)}</Text>)}</Section>
 <Section title="Can I afford this?"><Text style={s.muted}>Enter a purchase amount. Bills and savings are considered before the answer.</Text><Field label="Purchase amount" value={afford} onChangeText={setAfford} keyboardType="decimal-pad" placeholder="$300"/><Button title="Check my plan" onPress={checkAfford}/>{affordAnswer?<Text style={s.answer}>{affordAnswer}</Text>:null}</Section>
 <Section title="Ask about money"><Text style={s.muted}>The assistant receives only the minimum context for your current question. Money details are never saved as assistant memory automatically.</Text>{['How much can I spend today?','What bills are coming up?','Can I afford this?','Help me make a budget.','Where is my money going?','What can I cut back on?'].map(p=><Mini key={p} label={p} onPress={()=>navigation.navigate('Chat',{category:'Money',prompt:p})}/>)}</Section>
 <Section title="Budget setup"><Text style={s.muted}>Update your pay, savings plan, flexible targets, and recurring bills.</Text><Button title={budget?'Update Budget':'Set Up Budget'} secondary onPress={()=>navigation.navigate('BudgetSetup')}/></Section>
 </ScrollView>;
}
function Section({title,action,onAction,children}:{title:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <View style={s.section}><View style={s.sectionHead}><Text style={s.title}>{title}</Text>{action&&<Mini label={action} onPress={onAction!}/>}</View>{children}</View>};
function Mini({label,onPress,active=false}:{label:string;onPress:()=>void;active?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.mini,active&&s.miniActive]}><Text style={[s.miniText,active&&{color:'white'}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({screen:{backgroundColor:colors.cream},page:{padding:18,paddingBottom:44,gap:14},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:colors.cream},hero:{...card,backgroundColor:colors.paleGreen,gap:10},eyebrow:{fontWeight:'800',letterSpacing:1,color:colors.green},amount:{fontSize:44,fontWeight:'800',color:colors.ink},heroText:{fontSize:17,lineHeight:24,color:colors.ink,fontWeight:'600'},disclaimer:{fontSize:12,lineHeight:17,color:colors.muted},section:{...card,gap:12},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},title:{fontSize:19,fontWeight:'800',color:colors.ink,textTransform:'uppercase',flex:1},muted:{color:colors.muted,lineHeight:20},form:{gap:11,backgroundColor:colors.cream,padding:12,borderRadius:12},item:{flexDirection:'row',gap:10,borderTopWidth:1,borderTopColor:colors.border,paddingTop:11},grow:{flex:1,color:colors.ink},date:{fontSize:13,fontWeight:'700',color:colors.green},itemTitle:{fontWeight:'700',color:colors.ink,lineHeight:22},mini:{paddingVertical:7,paddingHorizontal:10,borderRadius:10,backgroundColor:colors.paleGreen,marginVertical:2},miniActive:{backgroundColor:colors.green},miniText:{color:colors.green,fontWeight:'700',fontSize:13},line:{flexDirection:'row',borderTopWidth:1,borderTopColor:colors.border,paddingTop:10},row:{flexDirection:'row',gap:8},answer:{backgroundColor:colors.paleGreen,padding:13,borderRadius:12,color:colors.ink,fontSize:16,lineHeight:23}});
