import React,{useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {api} from '../services/api'; import {Task} from '../types'; import {card,colors} from '../theme'; import {AssistantBannerAd} from '../components/AssistantBannerAd';

type Section='Today'|'Upcoming'|'Overdue'|'Completed';
const day=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();
export function TaskListScreen({navigation}:any){
 const [tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState<'Date'|'Priority'>('Date');
 const load=useCallback(()=>{setLoading(true);api.getTasks().then(setTasks).finally(()=>setLoading(false));},[]); useFocusEffect(useCallback(()=>{load();},[load]));
 const now=day(new Date()); const visible=tasks.filter(t=>(category==='All'||t.category===category)&&`${t.title} ${t.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Priority'?({High:0,Medium:1,Low:2}[a.priority]-{High:0,Medium:1,Low:2}[b.priority]):+(new Date(a.dueDate||'2999'))-+(new Date(b.dueDate||'2999')));
 const groups:Record<Section,Task[]>={Today:[],Upcoming:[],Overdue:[],Completed:[]}; visible.forEach(t=>{if(t.completed)groups.Completed.push(t);else if(t.dueDate&&day(new Date(t.dueDate))<now)groups.Overdue.push(t);else if(t.dueDate&&day(new Date(t.dueDate))===now)groups.Today.push(t);else groups.Upcoming.push(t);});
 const toggle=async(t:Task)=>{setTasks(x=>x.map(v=>v.id===t.id?{...v,completed:!v.completed}:v));try{await api.completeTask(t.id,!t.completed);}catch{load();}};
 return <ScrollView style={s.screen} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Pressable style={s.add} onPress={()=>navigation.getParent()?.navigate('TaskDetail')}><Text style={s.addText}>＋ Add task or reminder</Text></Pressable><TextInput style={s.search} value={query} onChangeText={setQuery} placeholder="Search tasks" placeholderTextColor={colors.muted}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{['All','Personal','Work','Shopping','Finance','Health','Family','Other'].map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.chipOn]}><Text style={category===c?s.chipTextOn:s.chipText}>{c}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>setSort(v=>v==='Date'?'Priority':'Date')}><Text style={s.sort}>Sort: {sort} ↕</Text></Pressable>{loading?<ActivityIndicator color={colors.green}/>:((['Today','Upcoming','Overdue','Completed'] as Section[]).map(name=><View key={name} style={s.section}><Text style={[s.heading,name==='Overdue'&&{color:colors.danger}]}>{name} · {groups[name].length}</Text>{groups[name].length?groups[name].map(t=><Pressable key={t.id} style={s.task} onPress={()=>navigation.getParent()?.navigate('TaskDetail',{taskId:t.id})}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:t.completed}} onPress={()=>toggle(t)} style={[s.check,t.completed&&s.checked]}><Text style={{color:'white'}}>{t.completed?'✓':''}</Text></Pressable><View style={{flex:1}}><Text style={[s.title,t.completed&&s.done]}>{t.title}</Text><Text style={s.meta}>{t.category} · {t.priority}{t.dueDate?` · ${new Date(t.dueDate).toLocaleDateString()}`:''}</Text>{t.category==='Shopping'&&t.checklist?.length?<Text style={s.meta}>{t.checklist.filter(i=>i.completed).length}/{t.checklist.length} items</Text>:null}</View><Text style={s.arrow}>›</Text></Pressable>):<Text style={s.empty}>Nothing here.</Text>}</View>))}<AssistantBannerAd /></ScrollView>;
}
const s=StyleSheet.create({screen:{backgroundColor:colors.cream},page:{padding:16,paddingBottom:40,gap:12},add:{minHeight:56,borderRadius:16,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},addText:{color:'white',fontSize:17,fontWeight:'800'},search:{backgroundColor:'white',borderWidth:1,borderColor:colors.border,borderRadius:14,minHeight:50,paddingHorizontal:15,fontSize:16,color:colors.ink},chips:{gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:18,backgroundColor:'white',borderWidth:1,borderColor:colors.border},chipOn:{backgroundColor:colors.green},chipText:{color:colors.ink},chipTextOn:{color:'white',fontWeight:'700'},sort:{color:colors.green,fontWeight:'700',textAlign:'right'},section:{...card,gap:7},heading:{fontSize:19,fontWeight:'800',color:colors.ink},task:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:10,borderTopWidth:1,borderTopColor:colors.border},check:{width:28,height:28,borderRadius:9,borderWidth:2,borderColor:colors.green,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:colors.green},title:{fontSize:16,fontWeight:'700',color:colors.ink},done:{textDecorationLine:'line-through',color:colors.muted},meta:{color:colors.muted,fontSize:13,marginTop:3},arrow:{fontSize:25,color:colors.green},empty:{color:colors.muted,paddingVertical:8}});
