import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { colors, card } from '../theme';
import { defaultWidgetPreferences, getWidgetPreferences, saveWidgetPreferences } from '../services/WidgetDataService';
import { WidgetPreferences, WidgetType } from '../types';
const types:{value:WidgetType;label:string}[]=[{value:'dailyBrief',label:'Daily Brief'},{value:'money',label:'Money'},{value:'calendar',label:'Calendar'},{value:'tasks',label:'Tasks'},{value:'minimal',label:'Minimal'}];
export function WidgetSettingsScreen({navigation}:any){
 const [prefs,setPrefs]=useState<WidgetPreferences>(defaultWidgetPreferences); const [saved,setSaved]=useState('');
 useEffect(()=>{getWidgetPreferences().then(value=>{setPrefs(value); if(value===defaultWidgetPreferences) Alert.alert('Home Screen privacy','Do you want money amounts and event names visible on your Home Screen?',[{text:'Keep It Private',onPress:()=>setPrefs(p=>({...p,privacyMode:true}))},{text:'Show Details',onPress:()=>setPrefs(p=>({...p,privacyMode:false}))}]);});},[]);
 const toggle=(key:keyof WidgetPreferences)=>(value:boolean)=>setPrefs(p=>({...p,[key]:value}));
 async function save(){await saveWidgetPreferences(prefs);setSaved('Saved on this device' );}
 return <ScrollView contentContainerStyle={s.page}><Text style={s.intro}>Choose what is useful at a glance. New widgets start private, and you can change this any time.</Text><Text style={s.heading}>Widget type</Text><View style={s.types}>{types.map(t=><Pressable key={t.value} onPress={()=>setPrefs(p=>({...p,type:t.value}))} style={[s.pill,prefs.type===t.value&&s.selected]}><Text style={[s.pillText,prefs.type===t.value&&s.selectedText]}>{t.label}</Text></Pressable>)}</View><View style={s.group}><Toggle label="Show greeting" value={prefs.showGreeting} onValueChange={toggle('showGreeting')}/><Toggle label="Show Money" value={prefs.showMoney} onValueChange={toggle('showMoney')}/><Toggle label="Show Calendar" value={prefs.showCalendar} onValueChange={toggle('showCalendar')}/><Toggle label="Show Email" value={prefs.showEmail} onValueChange={toggle('showEmail')}/><Toggle label="Show Tasks" value={prefs.showTasks} onValueChange={toggle('showTasks')}/><Toggle label="Privacy mode" detail="Hide money amounts and event names" value={prefs.privacyMode} onValueChange={toggle('privacyMode')}/></View><Pressable style={s.save} onPress={save}><Text style={s.saveText}>Save widget settings</Text></Pressable>{saved?<Text style={s.saved}>{saved}</Text>:null}<Pressable style={s.preview} onPress={async()=>{await saveWidgetPreferences(prefs);navigation.navigate('WidgetPreview');}}><Text style={s.previewText}>Open live widget preview</Text></Pressable><Text style={s.note}>The preview works in Expo Go. A real Home Screen widget requires a native EAS development build.</Text></ScrollView>;
}
function Toggle({label,detail,...props}:{label:string;detail?:string;value:boolean;onValueChange:(v:boolean)=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.label}>{label}</Text>{detail?<Text style={s.detail}>{detail}</Text>:null}</View><Switch trackColor={{true:colors.green}} {...props}/></View>}
const s=StyleSheet.create({page:{padding:20,gap:16},intro:{fontSize:16,lineHeight:23,color:colors.muted},heading:{fontSize:18,fontWeight:'800',color:colors.ink},types:{flexDirection:'row',flexWrap:'wrap',gap:8},pill:{paddingHorizontal:14,paddingVertical:10,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border},selected:{backgroundColor:colors.green,borderColor:colors.green},pillText:{color:colors.ink,fontWeight:'600'},selectedText:{color:'#fff'},group:{...card,padding:0,overflow:'hidden'},row:{minHeight:62,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:colors.border},label:{fontSize:16,color:colors.ink,fontWeight:'600'},detail:{fontSize:12,color:colors.muted,marginTop:3},save:{backgroundColor:colors.green,borderRadius:14,padding:16,alignItems:'center'},saveText:{color:'#fff',fontSize:16,fontWeight:'800'},saved:{textAlign:'center',color:colors.green},preview:{padding:14,alignItems:'center'},previewText:{color:colors.green,fontWeight:'800'},note:{color:colors.muted,fontSize:13,lineHeight:19,textAlign:'center'}});
