import { googleAccounts, GOOGLE_SCOPES, GoogleConnectionError } from './GoogleAccountService.js';
export type CalendarEvent={id:string;title:string;start:string;end:string;location:string;description:string};
async function googleGet(token:string,path:string,params:Record<string,string>={}) { const u=new URL(`https://www.googleapis.com/calendar/v3/${path}`); Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v)); const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`}}); const data:any=await r.json(); if(r.status===401) throw new GoogleConnectionError('reconnect','Your Google connection needs to be refreshed.'); if(!r.ok) throw new GoogleConnectionError('google','We could not reach your calendar. Please try again.'); return data; }
export class GoogleCalendarService {
  async getEventsBetween(userId:string,start:Date|string,end:Date|string):Promise<CalendarEvent[]> { const token=await googleAccounts.token(userId,GOOGLE_SCOPES.calendar); const data=await googleGet(token,'calendars/primary/events',{timeMin:new Date(start).toISOString(),timeMax:new Date(end).toISOString(),singleEvents:'true',orderBy:'startTime'}); return (data.items||[]).map((e:any)=>({id:e.id,title:e.summary||'Untitled event',start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,location:e.location||'',description:e.description||''})); }
  private bounds(offset:number) { const d=new Date(); d.setDate(d.getDate()+offset); d.setHours(0,0,0,0); const end=new Date(d);end.setDate(end.getDate()+1);return [d,end] as const; }
  getTodayEvents(userId:string){const [s,e]=this.bounds(0);return this.getEventsBetween(userId,s,e);} getTomorrowEvents(userId:string){const [s,e]=this.bounds(1);return this.getEventsBetween(userId,s,e);}
  async getFreeTime(userId:string,date:string) { const day=new Date(`${date}T00:00:00`); if(Number.isNaN(day.valueOf())) throw new Error('Choose a valid date.'); const workStart=new Date(day);workStart.setHours(8);const workEnd=new Date(day);workEnd.setHours(18);const events=await this.getEventsBetween(userId,workStart,workEnd); const free:{start:string;end:string}[]=[]; let cursor=workStart; for(const event of events){const start=new Date(event.start),end=new Date(event.end);if(start>cursor)free.push({start:cursor.toISOString(),end:start.toISOString()});if(end>cursor)cursor=end;}if(cursor<workEnd)free.push({start:cursor.toISOString(),end:workEnd.toISOString()});return free; }
  async createEvent(userId:string,event:{title:string;start:string;end:string;location?:string;description?:string}) { const token=await googleAccounts.token(userId,GOOGLE_SCOPES.calendarWrite); const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({summary:event.title,start:{dateTime:event.start},end:{dateTime:event.end},location:event.location,description:event.description})});const e:any=await r.json();if(!r.ok)throw new GoogleConnectionError(r.status===401?'reconnect':'google','We could not add that event. Please try again.');return {id:e.id,title:e.summary,start:e.start.dateTime,end:e.end.dateTime,location:e.location||'',description:e.description||''}; }
}
export const googleCalendar=new GoogleCalendarService();
