import crypto from 'node:crypto';
import { query } from '../db.js';

export type GoogleFeature = 'calendar' | 'gmail';
const scopes = {
  calendar: ['https://www.googleapis.com/auth/calendar.readonly'],
  calendarWrite: ['https://www.googleapis.com/auth/calendar.events'],
  gmail: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.compose'],
};
const key = () => crypto.createHash('sha256').update(process.env.TOKEN_ENCRYPTION_KEY || '').digest();
function encrypt(value: string) { const iv=crypto.randomBytes(12); const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv); const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]); return [iv.toString('base64'),cipher.getAuthTag().toString('base64'),data.toString('base64')].join('.'); }
function decrypt(value: string) { const [i,t,d]=value.split('.'); const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64')); decipher.setAuthTag(Buffer.from(t,'base64')); return Buffer.concat([decipher.update(Buffer.from(d,'base64')),decipher.final()]).toString(); }
export class GoogleConnectionError extends Error { constructor(public code: 'reconnect'|'permission'|'configuration'|'google', message: string) { super(message); } }
export class GoogleAccountService {
  private config() { const {GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI,TOKEN_ENCRYPTION_KEY}=process.env; if(!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET||!GOOGLE_REDIRECT_URI||!TOKEN_ENCRYPTION_KEY) throw new GoogleConnectionError('configuration','Google connections are not available yet.'); return {GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI}; }
  authorizationUrl(userId:string, feature:GoogleFeature, write=false) { const c=this.config(); const payload=Buffer.from(JSON.stringify({userId,feature,nonce:crypto.randomBytes(12).toString('hex'),expires:Date.now()+600000})).toString('base64url'); const sig=crypto.createHmac('sha256',process.env.JWT_SECRET||'development-only').update(payload).digest('base64url'); const state=`${payload}.${sig}`; const requested=[...(feature==='calendar'?scopes.calendar:scopes.gmail),...(feature==='calendar'&&write?scopes.calendarWrite:[])]; const p=new URLSearchParams({client_id:c.GOOGLE_CLIENT_ID,redirect_uri:c.GOOGLE_REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:requested.join(' '),state}); return {url:`https://accounts.google.com/o/oauth2/v2/auth?${p}`,state}; }
  decodeState(state:string) { try { const [payload,sig]=state.split('.'); const expected=crypto.createHmac('sha256',process.env.JWT_SECRET||'development-only').update(payload).digest('base64url'); if(!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))) throw new Error(); const value=JSON.parse(Buffer.from(payload,'base64url').toString()) as {userId:string;feature:GoogleFeature;expires:number}; if(value.expires<Date.now()) throw new Error(); return value; } catch { throw new GoogleConnectionError('google','The connection could not be verified.'); } }
  async exchange(userId:string, code:string) { const c=this.config(); const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:c.GOOGLE_CLIENT_ID,client_secret:c.GOOGLE_CLIENT_SECRET,redirect_uri:c.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})}); const token:any=await response.json(); if(!response.ok) throw new GoogleConnectionError('google','Google could not finish connecting. Please try again.'); const existing=await query<any>('SELECT refresh_token,granted_scopes FROM connected_accounts WHERE user_id=$1 AND provider=$2',[userId,'google']); const refresh=token.refresh_token?encrypt(token.refresh_token):existing.rows[0]?.refresh_token; const granted=Array.from(new Set([...(existing.rows[0]?.granted_scopes||[]),...(token.scope||'').split(' ').filter(Boolean)])); await query(`INSERT INTO connected_accounts(user_id,provider,access_token,refresh_token,expires_at,granted_scopes) VALUES($1,'google',$2,$3,NOW()+($4||' seconds')::interval,$5) ON CONFLICT(user_id,provider) DO UPDATE SET access_token=$2,refresh_token=$3,expires_at=NOW()+($4||' seconds')::interval,granted_scopes=$5,updated_at=NOW()`,[userId,encrypt(token.access_token),refresh,String(token.expires_in||3600),granted]); }
  async status(userId:string) { const r=await query<any>("SELECT granted_scopes, expires_at, refresh_token IS NOT NULL AS refreshable FROM connected_accounts WHERE user_id=$1 AND provider='google'",[userId]); const a=r.rows[0]; const has=(list:string[])=>!!a&&list.some(s=>a.granted_scopes.includes(s)); return {calendar:{connected:has(scopes.calendar),needsReconnect:!!a&&!a.refreshable&&new Date(a.expires_at)<=new Date()},gmail:{connected:has(scopes.gmail),needsReconnect:!!a&&!a.refreshable&&new Date(a.expires_at)<=new Date()}}; }
  async disconnect(userId:string, feature:GoogleFeature) { const remove=feature==='calendar'?[...scopes.calendar,...scopes.calendarWrite]:scopes.gmail; const r=await query<any>("SELECT granted_scopes FROM connected_accounts WHERE user_id=$1 AND provider='google'",[userId]); if(!r.rows[0]) return; const remaining=r.rows[0].granted_scopes.filter((s:string)=>!remove.includes(s)); if(!remaining.length) await query("DELETE FROM connected_accounts WHERE user_id=$1 AND provider='google'",[userId]); else await query("UPDATE connected_accounts SET granted_scopes=$2,updated_at=NOW() WHERE user_id=$1 AND provider='google'",[userId,remaining]); }
  async token(userId:string, required:string[]) { const r=await query<any>("SELECT * FROM connected_accounts WHERE user_id=$1 AND provider='google'",[userId]); const a=r.rows[0]; if(!a) throw new GoogleConnectionError('reconnect','Connect Google first.'); if(!required.some(s=>a.granted_scopes.includes(s))) throw new GoogleConnectionError('permission','This action needs your permission. Reconnect Google to allow it.'); if(new Date(a.expires_at)>new Date(Date.now()+30000)) return decrypt(a.access_token); if(!a.refresh_token) throw new GoogleConnectionError('reconnect','Your Google connection needs to be refreshed.'); const c=this.config(); const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.GOOGLE_CLIENT_ID,client_secret:c.GOOGLE_CLIENT_SECRET,refresh_token:decrypt(a.refresh_token),grant_type:'refresh_token'})}); const token:any=await response.json(); if(!response.ok) throw new GoogleConnectionError('reconnect','Your Google connection needs to be refreshed.'); await query("UPDATE connected_accounts SET access_token=$2,expires_at=NOW()+($3||' seconds')::interval,updated_at=NOW() WHERE user_id=$1 AND provider='google'",[userId,encrypt(token.access_token),String(token.expires_in||3600)]); return token.access_token as string; }
}
export const googleAccounts=new GoogleAccountService();
export const GOOGLE_SCOPES=scopes;
