import { Router } from 'express';
import { z } from 'zod';
import { AuthRequest } from '../middleware/auth.js';
import { query } from '../db.js';

export const tasksRouter = Router();
const category = z.enum(['Personal','Work','Shopping','Finance','Health','Family','Other']);
const priority = z.enum(['Low','Medium','High']);
const input = z.object({ title:z.string().trim().min(1).max(240), description:z.string().max(4000).optional(), category:category.optional(), priority:priority.optional(), dueDate:z.string().datetime().nullable().optional(), reminderDate:z.string().datetime().nullable().optional(), source:z.string().max(40).optional(), checklist:z.array(z.object({id:z.string(),text:z.string().min(1).max(200),completed:z.boolean()})).max(100).optional() });
const row = (r:any) => ({id:r.id,userId:r.user_id,title:r.title,description:r.description,category:r.category,priority:r.priority,dueDate:r.due_date,reminderDate:r.reminder_date,completed:r.completed,source:r.source,checklist:r.checklist,createdAt:r.created_at,updatedAt:r.updated_at});

tasksRouter.get('/', async(req:AuthRequest,res,next)=>{try{const r=await query('SELECT * FROM tasks WHERE user_id=$1 ORDER BY completed,due_date NULLS LAST,created_at DESC',[req.userId]);res.json(r.rows.map(row));}catch(e){next(e);}});
tasksRouter.post('/', async(req:AuthRequest,res,next)=>{try{const b=input.parse(req.body);const r=await query('INSERT INTO tasks(user_id,title,description,category,priority,due_date,reminder_date,source,checklist) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.userId,b.title,b.description||'',b.category||'Personal',b.priority||'Medium',b.dueDate||null,b.reminderDate||null,b.source||'user',JSON.stringify(b.checklist||[])]);res.status(201).json(row(r.rows[0]));}catch(e){next(e);}});
tasksRouter.put('/:id', async(req:AuthRequest,res,next)=>{try{const b=input.partial().parse(req.body);const current=await query<any>('SELECT * FROM tasks WHERE id=$1 AND user_id=$2',[req.params.id,req.userId]);if(!current.rows[0]){res.status(404).json({error:'Task not found.'});return;}const v={...row(current.rows[0]),...b};const r=await query('UPDATE tasks SET title=$3,description=$4,category=$5,priority=$6,due_date=$7,reminder_date=$8,checklist=$9,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *',[req.params.id,req.userId,v.title,v.description,v.category,v.priority,v.dueDate,v.reminderDate,JSON.stringify(v.checklist||[])]);res.json(row(r.rows[0]));}catch(e){next(e);}});
tasksRouter.delete('/:id',async(req:AuthRequest,res,next)=>{try{await query('DELETE FROM tasks WHERE id=$1 AND user_id=$2',[req.params.id,req.userId]);res.status(204).end();}catch(e){next(e);}});
tasksRouter.post('/complete',async(req:AuthRequest,res,next)=>{try{const b=z.object({id:z.string().uuid(),completed:z.boolean().default(true)}).parse(req.body);const r=await query('UPDATE tasks SET completed=$3,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *',[b.id,req.userId,b.completed]);if(!r.rows[0]){res.status(404).json({error:'Task not found.'});return;}res.json(row(r.rows[0]));}catch(e){next(e);}});
tasksRouter.post('/postpone',async(req:AuthRequest,res,next)=>{try{const b=z.object({id:z.string().uuid(),dueDate:z.string().datetime(),reminderDate:z.string().datetime().nullable().optional()}).parse(req.body);const r=await query('UPDATE tasks SET due_date=$3,reminder_date=COALESCE($4,reminder_date),updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *',[b.id,req.userId,b.dueDate,b.reminderDate]);if(!r.rows[0]){res.status(404).json({error:'Task not found.'});return;}res.json(row(r.rows[0]));}catch(e){next(e);}});
