export type AnswerStyle = 'Short and simple' | 'Normal' | 'Detailed';
export type Profile = { firstName: string; country: string; preferredResponseStyle: AnswerStyle; primaryHelpCategory: string };
export type Memory = { id: string; category: string; value: string; source: string; confirmedByUser: boolean };
export type Message = { id: string; role: 'user' | 'assistant'; content: string };
export type RootStackParamList = { Welcome: undefined; Login: undefined; Register: undefined; FirstSetup: { firstName?: string; token?: string; guest?: boolean } | undefined; Main: undefined; Guided: { category: string }; Chat: { category?: string; prompt?: string } | undefined; ConnectedServices: undefined; CalendarAssistant: undefined; EmailAssistant: undefined };
export type IntegrationStatus={calendar:{connected:boolean;needsReconnect:boolean};gmail:{connected:boolean;needsReconnect:boolean}};
export type CalendarEvent={id:string;title:string;start:string;end:string;location:string;description:string};
export type EmailMessage={id:string;threadId:string;from:string;to:string;subject:string;date:string;snippet:string;body:string};
export type TabParamList = { Home: undefined; Memory: undefined; Settings: undefined };
